name: CI/CD Pipeline
on:
  push:
    branches:
      - ci_cd

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps: 
      - name: build
        run: |
          echo "Building the project..."
          # Add your build script here

  deploy-staging:
    needs: build-and-test
    if: github.ref == 'refs/heads/ci_cd'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Add your deployment script here

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build-and-publish, deploy-dev]
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
