name: CI/CD Pipeline

on:
  push:
    branches:
      - ci_cd

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps: 
      - name: Build
        run: |
          echo "Building the project..."
          # Add your build script here

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ci_cd'
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment.."
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: jigsawml/code-repos-for-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: code-repos-for-test

  deploy-prod:
    needs: [build, deploy-staging]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ci_cd'
    environment:
      name: production
      url: https://production.example.com
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Add your production deployment script here
